# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yd43FDYkiOhKi3NqCr0ybzO-Yps5JDly
"""


import streamlit as st
import numpy as np
import joblib

# ----------------------------
# Page Config
# ----------------------------
st.set_page_config(
    page_title="Exoplanet Habitability Predictor",
    page_icon="🪐",
    layout="wide"
)

# ----------------------------
# Load Model
# ----------------------------
model = joblib.load("exoplanet_model.pkl")

# If you used scaler, uncomment below:
# scaler = joblib.load("scaler.pkl")

# ----------------------------
# Sidebar
# ----------------------------
st.sidebar.title("🚀 About This Project")

st.sidebar.info("""
This machine learning model predicts whether an exoplanet
is potentially habitable based on astrophysical parameters.

Model Used:
- Random Forest Classifier
- Class Balanced
- Trained on cleaned NASA Exoplanet dataset

Built with:
- Scikit-Learn
- Streamlit
- Python
""")

st.sidebar.success("Developed by Sarthak")

# ----------------------------
# Main Title
# ----------------------------
st.title("🪐 Exoplanet Habitability Prediction System")
st.markdown("### Enter planetary parameters to evaluate habitability potential")

st.write("---")

# ----------------------------
# Input Section
# ----------------------------
col1, col2 = st.columns(2)

with col1:
    planet_mass = st.number_input("Planet Mass (Earth Mass)", min_value=0.0)
    planet_radius = st.number_input("Planet Radius (Earth Radius)", min_value=0.0)
    orbital_period = st.number_input("Orbital Period (days)", min_value=0.0)
    semi_major_axis = st.number_input("Semi Major Axis (AU)", min_value=0.0)

with col2:
    equilibrium_temp = st.number_input("Equilibrium Temperature (K)", min_value=0.0)
    stellar_mass = st.number_input("Stellar Mass (Solar Mass)", min_value=0.0)
    stellar_radius = st.number_input("Stellar Radius (Solar Radius)", min_value=0.0)
    stellar_temp = st.number_input("Stellar Temperature (K)", min_value=0.0)

st.write("---")

# ----------------------------
# Prediction
# ----------------------------
if st.button("🔍 Predict Habitability"):

    features = np.array([[planet_mass,
                          planet_radius,
                          orbital_period,
                          semi_major_axis,
                          equilibrium_temp,
                          stellar_mass,
                          stellar_radius,
                          stellar_temp]])

    # If scaler used:
    # features = scaler.transform(features)

    prediction = model.predict(features)[0]
    probability = model.predict_proba(features)[0]

    if prediction == 1:
        st.success("🌍 This exoplanet is likely HABITABLE!")
    else:
        st.error("☄️ This exoplanet is NOT likely habitable.")

    st.subheader("Prediction Confidence")
    st.write(f"Habitable Probability: {round(probability[1]*100,2)}%")
    st.write(f"Non-Habitable Probability: {round(probability[0]*100,2)}%")

# ----------------------------
# Footer Info
# ----------------------------
st.write("---")
st.markdown("""
### 🔬 How It Works

The model analyzes planetary and stellar characteristics such as:
- Mass and Radius
- Orbital Properties
- Stellar Temperature and Size

Using ensemble learning (Random Forest), it classifies whether
conditions may support habitability.

This is a predictive ML system and not an astronomical confirmation.
""")

