# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yd43FDYkiOhKi3NqCr0ybzO-Yps5JDly
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt

# ----------------------------
# Page Config
# ----------------------------
st.set_page_config(
    page_title="Exoplanet Habitability Dashboard",
    page_icon="🪐",
    layout="wide"
)

# ----------------------------
# Load Artifacts
# ----------------------------
model = joblib.load("exoplanet_model.pkl")
feature_columns = joblib.load("feature_columns.pkl")

# ----------------------------
# Title
# ----------------------------
st.title("🪐 Exoplanet Habitability Analytics Dashboard")
st.markdown("Predict planetary habitability using a trained Random Forest model.")

st.write("---")

# ----------------------------
# Layout Columns
# ----------------------------
col1, col2 = st.columns(2)

with col1:
    st.subheader("Planet Parameters")
    planet_mass = st.number_input("Planet Mass (Earth Mass)", 0.0)
    planet_radius = st.number_input("Planet Radius (Earth Radius)", 0.0)
    orbital_period = st.number_input("Orbital Period (days)", 0.0)
    semi_major_axis = st.number_input("Semi Major Axis (AU)", 0.0)

with col2:
    st.subheader("Stellar Parameters")
    equilibrium_temp = st.number_input("Equilibrium Temperature (K)", 0.0)
    stellar_mass = st.number_input("Stellar Mass (Solar Mass)", 0.0)
    stellar_radius = st.number_input("Stellar Radius (Solar Radius)", 0.0)
    stellar_temp = st.number_input("Stellar Temperature (K)", 0.0)

st.write("---")

# ----------------------------
# Prediction
# ----------------------------
if st.button("🚀 Run Habitability Analysis"):

    # Create input dictionary
    input_dict = {
        "P_MASS": planet_mass,
        "P_RADIUS": planet_radius,
        "P_PERIOD": orbital_period,
        "P_SEMI_MAJOR_AXIS": semi_major_axis,
        "P_TEMP_EQUIL": equilibrium_temp,
        "S_MASS": stellar_mass,
        "S_RADIUS": stellar_radius,
        "S_TEMP": stellar_temp
    }

    # Convert to DataFrame
    input_df = pd.DataFrame([input_dict])

    # Add any missing columns
    for col in feature_columns:
        if col not in input_df.columns:
            input_df[col] = 0

    # Reorder columns to match training
    input_df = input_df[feature_columns]

    # Quick structural check
    st.write("Input shape:", input_df.shape)

    # ----------------------------
    # Safe Prediction
    # ----------------------------
    try:
        prediction = model.predict(input_df)[0]
        probability = model.predict_proba(input_df)[0]

        st.subheader("🧠 Prediction Result")

        label_map = {
            0: "☄️ Non-Habitable",
            1: "🪐 Potentially Habitable",
            2: "🌍 Highly Habitable"
        }

        st.success(f"Prediction: {label_map.get(prediction, prediction)}")
        st.write(f"Confidence Score: {round(max(probability) * 100, 2)}%")

        # ----------------------------
        # Probability Chart
        # ----------------------------
        st.subheader("📊 Probability Distribution")

        class_labels = [label_map.get(c, str(c)) for c in model.classes_]

        fig = plt.figure()
        plt.bar(class_labels, probability)
        plt.ylabel("Probability")
        plt.xticks(rotation=20)
        st.pyplot(fig)

        # ----------------------------
        # Feature Importance
        # ----------------------------
        st.subheader("🔬 Top Feature Importance")

        importances = model.feature_importances_
        indices = np.argsort(importances)[-10:]

        fig2 = plt.figure()
        plt.barh(range(len(indices)), importances[indices])
        plt.yticks(range(len(indices)), [feature_columns[i] for i in indices])
        plt.xlabel("Importance Score")
        st.pyplot(fig2)

    except Exception as e:
        st.error("Prediction Failed ⚠️")
        st.write("Error Details:", e)

st.write("---")

# ----------------------------
# Sidebar
# ----------------------------
st.sidebar.title("🚀 Project Overview")
st.sidebar.info("""
Machine Learning Model:
- Random Forest Classifier
- Multi-Class Classification
- Feature-Aligned Input

Deployment:
- Model + Feature Columns
- Built using Streamlit
""")

st.sidebar.success("Developed by Sarthak")

